"""
generate_review_queue.py

Module 5 data prep: applies the confidence/anomaly/high-stakes gate rules
to the validation set, picks a sample of gated patients, and generates a
plain-English SHAP explanation for each -- exported as JSON for the
human-in-the-loop review UI to consume.

Gate rules (all OR'd together -- any one triggers review):
  - Low confidence: predicted risk is very close to the model's decision
    threshold (the model is on the fence about flagging this patient)
  - Anomaly flagged: Module 3's Isolation Forest flagged this patient
  - High stakes: predicted risk is in the top 8% of the model's own output
"""

import json
import pickle
import re
from pathlib import Path

import numpy as np
import pandas as pd
import shap

from risk_model import local_slope, predict_risk, raw_proba

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "processed"
MODEL_PATH = ROOT / "models" / "rf_model.pkl"
OUT_PATH = ROOT / "outputs" / "review_queue.json"
UI_PATH = ROOT / "app" / "human_review_ui.html"

N_SAMPLE = 18
# NOTE: the model is now calibrated (no class weighting), so predicted risk
# is a real probability centered on the ~9% base rate -- NOT on 0.5. Fixed
# cutoffs like ">=0.70" would never trigger, so we use PERCENTILES of the
# model's own output instead.
#   - High stakes: top 8% of predicted risk.
#   - Low confidence: the 10% of patients closest to the decision threshold
#     saved by train_baseline.py (the cutoff that flags the top 20%).
HIGH_STAKES_PERCENTILE = 0.92
LOW_CONF_PERCENTILE = 0.10
# used only if the model bundle has no threshold
FALLBACK_THRESHOLD_PERCENTILE = 0.80

READABLE = {
    "number_inpatient": "prior inpatient stays",
    "total_prior_visits": "total prior visits",
    "time_in_hospital": "length of this hospital stay",
    "num_medications": "number of medications",
    "number_diagnoses": "number of diagnoses recorded",
    "discharge_disposition_id": "discharge disposition (where they're sent after leaving)",
    "num_lab_procedures": "number of lab procedures run",
    "has_prior_emergency": "history of ER visits",
    "payer_code_Missing": "missing payer/insurance info",
    "diabetesMed_Yes": "currently on diabetes medication",
}


def readable_name(feat: str) -> str:
    if feat in READABLE:
        return READABLE[feat]
    if feat.startswith("age_"):
        return f"age bracket {feat[4:]}"
    return feat.replace("_", " ")


def build_X(df, bundle):
    num = df[bundle["num_cols"]].fillna(0).to_numpy()
    cat = bundle["encoder"].transform(df[bundle["cat_cols"]].astype(str))
    return np.hstack([num, cat])


def gate_reasons(row, high_stakes_cut, low_conf_cut, decision_threshold) -> list:
    reasons = []
    if abs(row["predicted_risk"] - decision_threshold) <= low_conf_cut:
        reasons.append("Low model confidence")
    if row["is_anomaly"] == 1:
        reasons.append("Anomaly flagged (Module 3)")
    if row["predicted_risk"] >= high_stakes_cut:
        reasons.append("High-stakes prediction")
    return reasons


def inject_into_ui(records, decision_threshold, high_stakes_cut, base_rate):
    """Rewrite the data block inside the review UI so it always matches the
    latest model run (cases, color thresholds, and the average-patient rate)."""
    if not UI_PATH.exists():
        print(f"UI file not found, skipped -> {UI_PATH}")
        return
    html = UI_PATH.read_text(encoding="utf-8")
    pattern = re.compile(r"// BEGIN_DATA.*?// END_DATA", re.S)
    if not pattern.search(html):
        print("UI markers (// BEGIN_DATA ... // END_DATA) not found, skipped")
        return
    block = (
        "// BEGIN_DATA (auto-generated by src/generate_review_queue.py -- do not edit by hand)\n"
        f"const CASES = {json.dumps(records)};\n"
        f"const DECISION_THRESHOLD = {decision_threshold:.3f};\n"
        f"const HIGH_STAKES_CUT = {high_stakes_cut:.3f};\n"
        f"const BASE_RATE = {base_rate:.3f};\n"
        "// END_DATA"
    )
    UI_PATH.write_text(pattern.sub(lambda m: block, html), encoding="utf-8")
    print(f"Updated review UI -> {UI_PATH}")


def run():
    with open(MODEL_PATH, "rb") as f:
        bundle = pickle.load(f)
    model = bundle["model"]
    feature_names = bundle["feature_names"]

    val = pd.read_csv(f"{DATA_DIR}/val.csv")
    X_val = build_X(val, bundle)
    val["predicted_risk"] = predict_risk(bundle, X_val)

    decision_threshold = bundle.get("threshold")
    if decision_threshold is None:
        decision_threshold = float(
            val["predicted_risk"].quantile(FALLBACK_THRESHOLD_PERCENTILE))

    high_stakes_cut = val["predicted_risk"].quantile(HIGH_STAKES_PERCENTILE)
    dist_from_threshold = (val["predicted_risk"] - decision_threshold).abs()
    low_conf_cut = dist_from_threshold.quantile(LOW_CONF_PERCENTILE)
    print(f"Decision threshold: {decision_threshold:.3f}")
    print(f"Calibrated cutoffs -- high-stakes: risk >= {high_stakes_cut:.3f}  |  "
          f"low-confidence: |risk-{decision_threshold:.3f}| <= {low_conf_cut:.3f}")

    gated_mask = (
        (dist_from_threshold <= low_conf_cut)
        | (val["is_anomaly"] == 1)
        | (val["predicted_risk"] >= high_stakes_cut)
    )
    gated = val[gated_mask].copy()
    print(f"{gated_mask.sum():,} of {len(val):,} patients ({gated_mask.mean():.1%}) hit the review gate")

    # Sample a mix so the UI shows variety, not all one gate reason
    sample = gated.sample(n=min(N_SAMPLE, len(gated)),
                          random_state=7).reset_index(drop=True)
    X_sample = build_X(sample, bundle)

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_sample)
    if isinstance(shap_values, list):
        shap_pos = shap_values[1]
    elif shap_values.ndim == 3:
        shap_pos = shap_values[:, :, 1]
    else:
        shap_pos = shap_values

    # SHAP is computed on the raw forest; rescale each patient's contributions by the
    # local slope of the calibration curve so they match the displayed (calibrated) risk.
    slopes = local_slope(bundle.get("calibration"),
                         raw_proba(bundle, X_sample))

    records = []
    for i, row in sample.iterrows():
        contributions = sorted(
            zip(feature_names, shap_pos[i]), key=lambda x: abs(x[1]), reverse=True)[:3]
        effects = [round(float(v) * float(slopes[i]), 4)
                   for _, v in contributions]
        reasons = []
        for feat, val_ in contributions:
            direction = "increased" if val_ > 0 else "decreased"
            reasons.append(f"{readable_name(feat)} {direction} risk")

        records.append({
            "id": int(row["patient_nbr"]),
            "age": row["age"],
            "gender": row["gender"],
            "admission_type_id": int(row["admission_type_id"]),
            "time_in_hospital": int(row["time_in_hospital"]),
            "num_medications": int(row["num_medications"]),
            "number_inpatient": int(row["number_inpatient"]),
            "number_diagnoses": int(row["number_diagnoses"]),
            "diag_1_group": row["diag_1_group"],
            "predicted_risk": round(float(row["predicted_risk"]), 3),
            "is_anomaly": bool(row["is_anomaly"]),
            "gate_reasons": gate_reasons(row, high_stakes_cut, low_conf_cut, decision_threshold),
            "top_reasons": reasons,
            "reason_effects": effects,
            "actual_outcome": "Readmitted <30d" if row["readmitted_30d"] == 1 else "Not readmitted",
        })

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(records, f, indent=2)
    print(f"Wrote {len(records)} review cases -> {OUT_PATH}")

    inject_into_ui(records, decision_threshold, float(high_stakes_cut),
                   float(val["readmitted_30d"].mean()))


if __name__ == "__main__":
    run()
